#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

mkdir /tmp/algodoo-path/ -p
cd /tmp/algodoo-path/
p7zip -f -k -d /tmp/algodoo-wine.7z
cd -
chmod 777 -R /tmp/algodoo-path/

function geraShort {
	echo "[Desktop Entry]"
	echo "Type=Link"
	cat "$1" | \
	grep "Name=" | head -n1
	cat "$1" | \
	grep "Name[pt_BR]=" | head -n1
	cat "$1" | \
	grep "Icon=" | head -n1
	echo "URL=$2"
}

while read USUARIO; do
	runuser -l $USUARIO -c "rsync -a /tmp/algodoo-path/ /home/$USUARIO/"
	runuser -l $USUARIO -c 'wine regedit /tmp/algodoo-wine.reg'
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Algodoo.desktop > .local/share/applications/Algodoo.desktop"
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Reset\ Algodoo.desktop > .local/share/applications/Reset\ Algodoo.desktop"
	
	geraShort /home/$USUARIO/.local/share/applications/Algodoo.desktop \
	/home/$USUARIO/.local/share/applications/Algodoo.desktop \
	> /home/$USUARIO/Desktop/Algodoo.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list