#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

mkdir /tmp/algodoo-path/ -p
cd /tmp/algodoo-path/
p7zip -f -k -d /tmp/algodoo-wine.7z
cd -
chmod 777 -R /tmp/algodoo-path/
rm -rf /tmp/algodoo-path/.local/share/desktop-directories/education-Physics.directory
rm -rf /tmp/algodoo-path/.config/menus/applications-merged/algodoo.menu

while read USUARIO; do
	runuser -l $USUARIO -c "rsync -a /tmp/algodoo-path/ /home/$USUARIO/"
	runuser -l $USUARIO -c 'wine regedit /tmp/algodoo-wine.reg'
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Algodoo.desktop > .local/share/applications/Algodoo.desktop"
	runuser -l $USUARIO -c "sed 's/USUARIO/$USUARIO/g' /tmp/Reset\ Algodoo.desktop > .local/share/applications/Reset\ Algodoo.desktop"
	
	# geraShort /home/$USUARIO/.local/share/applications/Algodoo.desktop \
	# /home/$USUARIO/.local/share/applications/Algodoo.desktop \
	# > /home/$USUARIO/Desktop/Algodoo.desktop
	cp /home/$USUARIO/.local/share/applications/Algodoo.desktop /home/$USUARIO/Desktop/Algodoo.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list